print("Welcome! This program will ask you a few questions about yourself and create a summary of your responses.")
name = input("What is your name?")
college = input(name + " What college do you attend?")
highschool = input(name + " What highschool did you attend?")
school = input("Which school do you think is the most fun?")
age = input("How old are you?")
food = input("what is your favorite food?")
sport = input("what sport do you like the most?")
print("Your name is " + name + " \nyou attend " + college + " \nand you went to " + highschool + "\nYou think " + school + " is the more fun one out of the two")
print("You are " + age + " years old\nyour favorite food is " + food + ", nasty choice btw\nand your favorite sport is " + sport)
print("I bet that i am better than you in " + sport)
print("\nAnyways " + name + " thanks for the answers! Enjoy the rest of your day!......bozo")
